name: PR metadata annotation

on: 
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

jobs:
  log: 
    runs-on: ubuntu-latest
    name: Prints out the event context that the action received for quick debugging
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  omni-action:
    runs-on: ubuntu-latest
    name: Allows bot to perform automated actions for this repository
    steps:
      - name: Run omni-action
        uses: zackheil/omni-action@main
        with:
          context: ${{ toJson(github) }}
          
