name: Weekly Dependency Update Branch
on:
  schedule:
    - cron: "0 2 * * 6" 
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Create Branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Actions"
          git checkout -b dependabot-staging
          git commit --allow-empty -m "chore: Weekly Dependency Updates (Staging)"
          git push origin dependabot-staging
      - name: Create Draft PR for Updates
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.create({
              owner: "zackheil",
              repo: "gh-actions",
              title: "Weekly Dependency Updates",
              head: "dependabot-staging",
              base: "main",
              body: "Weekly Dependency Updates for NPM and GitHub Actions",
              draft: true,
              maintainer_can_modify: true
            })
